# Generated by Django 4.2.2 on 2023-06-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='details',
            new_name='interest',
        ),
    ]
